### ISSUE TITLE
Install on Unraid 

### ISSUE THREAD

**Issue by FraZe69** [Ulisses1478/Shinobi-Docker#1]
---------------------------------------------
Installing Shinobi
*Note : Default install location is "/shinobi"
Opening Install Location : "/"
*--------------------**---------------------*
Installing Shinobi
---------------------------------------------
fatal: destination path 'shinobi' already exists and is not an empty directory.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-------------------------------------
---------- Shinobi Systems ----------
Repository : https://gitlab.com/Shinobi-Systems/ShinobiCE
Product : Shinobi Community Editon (CE)
Branch : master
Version :

Date : Sun Apr 7 19:22:10 Europe 2019
-------------------------------------
-------------------------------------
*-----------------------------------*
chmod: cannot access 'INSTALL/start.sh': Not a directory
sudo: INSTALL/start.sh: command not found
---------------------------------------------
Installing Shinobi
*Note : Default install location is "/shinobi"
Opening Install Location : "/"
*--------------------**---------------------*
Installing Shinobi
---------------------------------------------
fatal: destination path 'shinobi' already exists and is not an empty directory.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-------------------------------------
---------- Shinobi Systems ----------
Repository : https://gitlab.com/Shinobi-Systems/ShinobiCE
Product : Shinobi Community Editon (CE)
Branch : master
Version :

Date : Sun Apr 7 19:23:22 Europe 2019
-------------------------------------
-------------------------------------
*-----------------------------------*
chmod: cannot access 'INSTALL/start.sh': Not a directory
sudo: INSTALL/start.sh: command not found

**Comment by khiles** [comment]
yea i get exact same message

**Comment by Ulisses1478** [comment]
Thank you for the feedback. The docker was updated and it's running fine. Just taking a bit to start. If you still getting some issues report me again.

**Comment by jthacker48** [comment]
I'm an Unraid user as well and running into the same issues with install.  I've got a couple of specific questions/issues as it relates to Unraid.

- Do I need to install mysql docker separately or does your community application for Shinobi contain a mysql instance?
- I attempted to change the network from Bridge to Br0 so I can assign a specific IP address.  Unfortunately, the container wouldn't assign network at all unless I was using Bridge.
- When I installed the container as a standalone without separate mysql container and using Bridge, I still wasn't able to access the webui.  I'm sure it is due to one of the issues above.

Thanks for your work!  I can't wait to get rid of that dinosaur, Zoneminder!!!

**Comment by Ulisses1478** [comment]
Hey, thanks for the feedback. 

No, you don’t need to install mysql and you can’t for now. It will be implemented

This is the first time i see this issue with network. i will take a look tomorrow

Standalone should work. I tested recently. Open another issue with the logs. So i can take look at this. Make sure you have all updated

**Comment by Ulisses1478** [comment]
@jthacker48 I forget to put your name here, you still can't access the web UI with default configs?
